@host = http://localhost:40000

# Login
###
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "username": "qwe",
  "password": "qwe"
}

# Dashboard
###
GET {{host}}/
Authorization: Bearer {{login.response.body.token}}

# Alunos
###
GET {{host}}/getAllAlunos
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/insertAlunos
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "nome": "Aluno Teste 2",
  "matricula": "VP305",
  "datanascimento": "06-01-2000"
}

###
POST {{host}}/getAlunoByID
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "alunoid": 4
}

###
POST {{host}}/updateAlunos
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "aluno_id": 3,
  "nome": "Aluno Teste Alterado",
  "matricula": "VP301-A",
  "datanascimento": "12-09-2000"
}

###
POST {{host}}/deleteAlunos
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "aluno_id": 3
}


# Professores
###
GET {{host}}/getAllProfessores
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/insertProfessores
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "nome": "Novo Professor Teste",
  "email": "professor.teste@escola.com"
}

###
POST {{host}}/getProfessorByID
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "professorid": 1
}

###
POST {{host}}/updateProfessores
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "professor_id": 1,
  "nome": "Professor Teste Alterado",
  "email": "professor.alterado@escola.com"
}

###
POST {{host}}/deleteProfessores
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "professor_id": 1
}


# Disciplinas
###
GET {{host}}/getAllDisciplinas
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/insertDisciplinas
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "nome_disciplina": "Web 3",
  "codigo_disciplina": "WEB3-2025",
  "professor_id": 1
}

###
POST {{host}}/getDisciplinaByID
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "disciplinaid": 1
}

###
POST {{host}}/updateDisciplinas
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "disciplina_id": 1,
  "nome_disciplina": "Web 3 (Atualizada)",
  "codigo_disciplina": "WEB3-2025-A",
  "professor_id": 1
}

###
POST {{host}}/deleteDisciplinas
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "disciplina_id": 1
}


# Matrículas
###
POST {{host}}/insertAlunoDisciplina
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "aluno_id": 4,
  "disciplina_id": 1
}

###
POST {{host}}/getDisciplinasByAlunoID
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "alunoid": 4
}

###
POST {{host}}/getAlunosByDisciplinaID
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "disciplinaid": 1
}

###
POST {{host}}/deleteAlunoDisciplina
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "aluno_id": 4,
  "disciplina_id": 1
}


# Logout
###
POST {{host}}/logout
Authorization: Bearer {{login.response.body.token}}